name: Simple pipeline
on: push
jobs:
  build:
    name: Creating EC2 instance on CloudFormation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: "Enes"
